title: Jausmy Longange's Data Analytics Portfolio
logo: assets/images/Portfolio Pic.png
description: Hello. Welcome to my data analytics portfolio page. Thanks for finding your way over here, and taking the time to check this out. This is where I will be uploading data projects that I have worked on and completed, as well as other interesting things that I have created in relation to data. If you would like to reach out to me, I can be contacted via email at Jausmy96@gmail.com or on [LinkedIN](https://www.linkedin.com/in/Jausmy)
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

